---
title: "Generated Report"
output: html_document
---

# Introduction

### Conservation Area

`r params$mpas`

### Objectives

```{r, echo=FALSE,comment=NA, results="asis"}
cat(Objectives[[which(tolower(areas) == tolower(NAME_to_tag(names=input$mpas)))]])
```


### Context

```{r, echo=FALSE,comment=NA, results="asis"}
cat(Context[[which(tolower(areas) == tolower(NAME_to_tag(names=input$mpas)))]])
```


```{r, echo=FALSE}
#cat(paste0("The area is ", params$coords[[input$mpas]]))
map <- leaflet() %>%
  addTiles() %>%
  addPolygons(lat = params$coords[[input$mpas]]$lat, lng = params$coords[[input$mpas]]$lng, fillColor = params$coords[[input$mpas]]$color, fillOpacity = 0.5, weight = 2, color="black")

map
```


# Results

```{r, echo=FALSE, comment=NA, results="asis"}
keeper <- indicator_to_plot[which(tolower(indicator_to_plot$area) == tolower(NAME_to_tag(names=input$mpas))),]

BINS <- unique(trimws(tolower(unlist(strsplit(keeper$indicator_bin, ";"))), "both"))

keeper2 <- NULL

for (i in seq_along(BINS)) {
  KK <- keeper[which(grepl(BINS[i],trimws(tolower(keeper$indicator_bin),"both"))),]
  
  keeper2[[i]] <- data.frame(
      Indicator = KK$indicators,
      Status = KK$status,
      Trend = KK$trend,
      Plot=KK$plot,
      Grade=KK$status_grade,
      Project=KK$project,
      stringsAsFactors = FALSE
    )

}

names(keeper2) <- BINS

for (i in seq_along(keeper2)) {
  cat(sprintf("### Indicator Bin: %s\n\n", BINS[i]))
  for (j in seq_along(keeper2[[i]]$Indicator)) {
    cat(sprintf("<b>Indicator: %s.</b>\n\n", keeper2[[i]]$Indicator[j]))
    if (!(keeper2[[i]]$Plot[j] == "0")) {
      plotty <- keeper2[[i]]$Plot[j]
      if (grepl("ah=ah", plotty)) {
        ah <- all_haddock
      }
      
      if (grepl("bd=bd", plotty)) {
        bd <- bloom_df
      }
      eval(parse(text=keeper2[[i]]$Plot[j]))
      cat(sprintf("%s.\n\n", " "))
      cat(sprintf("%s.\n\n", keeper2[[i]]$Status[j]))
      cat(sprintf("%s.\n\n", keeper2[[i]]$Trend[j]))
      cat(sprintf("%s.\n\n", " "))
      cat(sprintf("This indicator has a grade of: %s.\n\n", keeper2[[i]]$Grade[j]))
      cat(sprintf("%s.\n\n", " "))
      cat(sprintf("Data was provided from project %s.\n\n", keeper2[[i]]$Project[j]))


      
    }
    
  }
}




```

